name: Smart Scale Connect Garmin DI
version: "0.4.3-garmin-di"
slug: smart_scale_connect_garmin_di
description: SmartScaleConnect with patched Garmin DI OAuth2 authorization
url: "https://github.com/alexanderznamensky/home-assistant-addons/smartscaleconnect-ha-addon"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
init: false
map:
  - addon_config:rw
options:
  sleep: "24h"
schema:
  sleep: str
